version: '3'
services:
  postgres:
    image: postgres:11-alpine
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:5-alpine
    volumes:
      - redis:/data

  app:
    build: .
    volumes:
      - ./security:/app/security
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    env_file:
      - '.env.development'
      - '.env.development.local'
    environment:
      RAILS_ENV: production
      DATABASE_URL: postgres://postgres:@postgres:5432/slovensko-sk-api
      REDIS_URL: redis://redis:6379
      SECRET_KEY_BASE: <replace this with a secret>

volumes:
  postgres:
  redis: