default: &default
  adapter: postgresql
  encoding: unicode
  pool: 50

development:
  <<: *default
  database: podaas_development

test:
  <<: *default
  database: podaas_test

staging:
  url: <%= ENV['DATABASE_URL'] %>
  pool: 30

production:
  url: <%= ENV['DATABASE_URL'] %>
  pool: 50
