version: '3'
services:
  postgres:
    image: postgres:11-alpine
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:5-alpine
    volumes:
      - redis:/data

  app:
    image: skdigital/slovensko-sk-api:latest
    volumes:
      - ./security:/app/security
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - redis
    env_file:
      - '.env.production'
      - '.env.production.local'
    environment:
      DATABASE_URL: postgres://postgres:@postgres:5432/slovensko-sk-api
      REDIS_URL: redis://redis:6379
      SECRET_KEY_BASE: <replace this with a secret>

  worker:
    image: skdigital/slovensko-sk-api:latest
    command: bundle exec rake jobs:work
    volumes:
      - ./security:/app/security
    depends_on:
      - postgres
      - redis
    env_file:
      - '.env.production'
      - '.env.production.local'
    environment:
      DATABASE_URL: postgres://postgres:@postgres:5432/slovensko-sk-api
      REDIS_URL: redis://redis:6379
      SECRET_KEY_BASE: <replace this with a secret>

  clock:
    image: skdigital/slovensko-sk-api:latest
    command: bundle exec clockwork config/clock.rb
    volumes:
      - ./security:/app/security
    depends_on:
      - postgres
      - redis
    env_file:
      - '.env.production'
      - '.env.production.local'
    environment:
      DATABASE_URL: postgres://postgres:@postgres:5432/slovensko-sk-api
      REDIS_URL: redis://redis:6379
      SECRET_KEY_BASE: <replace this with a secret>

volumes:
  postgres:
  redis:
