version: '3'
services:
  postgres:
    image: postgres:11-alpine
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:5-alpine
    volumes:
      - redis:/data

  web:
    image: skdigital/slovensko-sk-api:latest
    volumes:
      - ./security:/app/security
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://postgres:@postgres:5432/slovensko-sk-api
      REDIS_URL: redis://redis:6379

volumes:
  postgres:
  redis:
